# Generated by Django 2.2.3 on 2019-07-21 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_fd', '0001_initial'),
        ('goods_fd', '0001_initial'),
        ('order_fd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfor',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.user_fd.Address', verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='orderinfor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.order_fd.OrderInfor', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.goods_fd.GoodsSKU', verbose_name='商品SKU'),
        ),
    ]
